public with sharing class HelloCICD {
    public static String sayHello() {
        //test
        return 'Hello from CI/CD POC';
    }
    /*
    public static String getGreeting(String name) {
        return 'Hello, ' + name;
    }
    
    public static Integer add(Integer a, Integer b) {
        return a + b;
    }
    
    public static Integer subtract(Integer a, Integer b) {
        return a - b;
    }
    
    public static String formatMessage(String msg) {
        return 'Message: ' + msg.toUpperCase();
    }*/
}
